---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-3"
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/
- node_modules/
- tmp/
- blueprints/*/files/**/*
